[2024-03-09T20:16:43.765+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_pipeline_dag.taskA manual__2024-03-09T14:46:40.571296+00:00 [queued]>
[2024-03-09T20:16:43.772+0530] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_pipeline_dag.taskA manual__2024-03-09T14:46:40.571296+00:00 [queued]>
[2024-03-09T20:16:43.773+0530] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-09T20:16:43.797+0530] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): taskA> on 2024-03-09 14:46:40.571296+00:00
[2024-03-09T20:16:43.801+0530] {standard_task_runner.py:60} INFO - Started process 23891 to run task
[2024-03-09T20:16:43.805+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'python_pipeline_dag', 'taskA', 'manual__2024-03-09T14:46:40.571296+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/execute_python_pipeline.py', '--cfg-path', '/tmp/tmpnyw0vlvv']
[2024-03-09T20:16:43.807+0530] {standard_task_runner.py:88} INFO - Job 79: Subtask taskA
[2024-03-09T20:16:43.865+0530] {task_command.py:423} INFO - Running <TaskInstance: python_pipeline_dag.taskA manual__2024-03-09T14:46:40.571296+00:00 [running]> on host BreakThrough.
[2024-03-09T20:16:44.024+0530] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kai' AIRFLOW_CTX_DAG_ID='python_pipeline_dag' AIRFLOW_CTX_TASK_ID='taskA' AIRFLOW_CTX_EXECUTION_DATE='2024-03-09T14:46:40.571296+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-09T14:46:40.571296+00:00'
[2024-03-09T20:16:44.033+0530] {logging_mixin.py:188} INFO - This is task A
[2024-03-09T20:16:44.043+0530] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/kai/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kai/airflow/dags/execute_python_pipeline.py", line 13, in read_csv_file
    df=pd.read_csv('/datasets/insurance.csv')
  File "/home/kai/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/kai/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/kai/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/kai/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/home/kai/.local/lib/python3.10/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/datasets/insurance.csv'
[2024-03-09T20:16:44.069+0530] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=python_pipeline_dag, task_id=taskA, execution_date=20240309T144640, start_date=20240309T144643, end_date=20240309T144644
[2024-03-09T20:16:44.121+0530] {standard_task_runner.py:107} ERROR - Failed to execute job 79 for task taskA ([Errno 2] No such file or directory: '/datasets/insurance.csv'; 23891)
[2024-03-09T20:16:44.140+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-09T20:16:44.158+0530] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
